### ISSUE TITLE
Finnassa lainahistorian järjestäminen nimekkeen, tekijän ja aineistotyypin mukaan

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Finna-kehitysehdotukset#16]
### Kehitysehdotukseni

Vanha toive, jota on odotettu jo Kohan alkuajoista lähtien. :)

Finnassa pystyisi järjestämään lainahistoriaa tekijän, nimekkeen ja aineistotyypin mukaan sekä tekemään hakuja omaan lainahistoriaan.

Tietojemme mukaan Finnan puolella on jo valmius toiminnallisuuksien käyttöönottoon.

**Comment by pknuuti** [comment]
Asiakkaat toivovat tätä säännöllisen epäsäännöllisesti.

**Comment by IrinaHalminen** [comment]
Ensiapuna (hakujen suhteen) asiakas voi luoda lainahistoriastaan suosikkilistan, jolta on helpompi hakea kuin monisivuisesta Finna-näkymästä. Sisäänkirjautuneena näkee teoksia selatessa teoksen tietojen yhteydessä, onko se jollain listalla, joka puolestaan auttaa hoksaamaan, onko teos luettu jne.

**Comment by AnneliO** [comment]
Finna-kehitysehdotukset-sivulta poimittu: Koha-yhteisön uudessa versiossa on rajapinnan sivutus _page ja sorttaus _order_by query parametrilla

**Comment by pknuuti** [comment]
Tästä asiasta on kysytty Finna kyselytunnilla 13.2.2024 ja Finnassa on luvattu ottaa asia uudelleen käsiteltäväksi.

**Comment by lmstrand** [comment]
Testi- ja Next-Finnoihin välittyy tällä hetkellä author-tieto (Koha-Suomi -muutos) ja aineistotyyppi-tieto (myös tuotannossa), joilla järjestely voidaan tehdä.

**Comment by IrinaHalminen** [comment]
Finnan lainaushistoriaan on tuotu näkyville myös poistettujen niteitten nimeketiedot (aiemmin nimekkeen kohdalla tekstinä näkyi ei otsikkoa). Jos valitsee otsikonmukaisen järjestyksen, nämä poistetut niteet näkyvät ensin ja niitten jälkeen muun lainaushistorian osalta aakkostus alkaa uudelleen alusta. Olisi hyvä, että myös poistetut nimikkeet aakkostuisivat otsikonmukaisesti muun lainaushistorian "sekaan".

**Comment by sksandel** [comment]
11.10.2024 Yhteinen läpikäynti. Suljetaan tuplana. Jäljelle jää https://github.com/KohaSuomi/Finna-kehitysehdotukset/issues/14
