### ISSUE TITLE
Damaged-tila yliajaa muut tilat Finnassa

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Finna-kehitysehdotukset#2]
Damaged-tilan tieto priorisoidaan Finnassa ennen Kuljetettavana-tilaa. Tämä on ongelmallista esim. Jokeri-niteiden (ei varattavissa, pikalaina) kanssa: nide saattaa olla kuljetuksessa takaisin kotikirjastoonsa, mutta näkyy verkkokirjastossa Saatavana, ei varattavissa -tilaisena. Damaged tilassa myös kotipalvelu ja koulukirjastojen niteitä.

Ihannetilanne on, että tilojen näytön priorisoinnin voisi itse määritellä.

Damaged-tila on Vaskissa Jokeri-käytössä, koska Oletusvaraussääntö aiheuttaa ongelmia saatavuustietojen hakemisessa Finnassa
https://github.com/KohaSuomi/Koha/issues/590

**Comment by AnneliO** [comment]
Pääkäyttäjät käsitteli 7.2.2023.

Susanna kerää erilaiset tilat ja tehdään pääkäyttäjäpalaverissa niille sitten priorisoitu listaus, joka toimitetaan Finna-toimistolle.

**Comment by sksandel** [comment]
Tässä pitäisi olla ne tilat, jotka näkyvät Finnassa.
1. LOST
2. Lainassa
3. Varattu (=Noudettavissa)
4. NOT_LOAN
5. Kuljetuksessa
6. Damaged
7. Saatavissa

**Comment by AnneliO** [comment]
Pääkäyttäjien viikkopalaveri 14.3.2023: Järjestys ok. Jos Finnassa ei pystytä tekemään näiden eteen muutoksia, niin sitten muutetaan Koha-kehitysehdotukseksi.

**Comment by sksandel** [comment]
Finnassa pystytään priorisoimaan tilat. Priorisointi on toteutettuna tällä hetkellä meidän testinäkymään vaski.finna-pre.fi, mutta sitä on ilman Kohaan pääsyä muiden hankala testata. Meidän testauksen perusteella kaikki näyttää menevän oikein. 

Miten edetään?

**Comment by AnneliO** [comment]
Lisäsin tiketin pääkäyttäjien esityslistalle ensi viikolle 16.

**Comment by sksandel** [comment]
Roosa huomasi, että siellä on sittenkin NOT_LOAN väärässä kohdassa:

Näyttäisi menevän näin (priorisoinnin numerointi säilytetty):

1.      LOST
2.      Lainassa
3.      Varattu (=Noudettavissa)
5.      Kuljetuksessa
6.      Damaged
4.      NOT_LOAN
7.      Saatavissa

Edit: Laitoin Finna-postiin NOT_LOAN-tilan virheellisen sijoittumisen.

**Comment by sksandel** [comment]
Kansalliskirjasto säätää prioriteetteja vielä. Sovimme 25.4. pääkäyttäjäpalaverissa pienen muutoksen prioriteettilistaukseen. NOT_LOAN ja Kuljetuksessa vaihtavat paikkaa. Tässä uusi toivejärjestys: 

1. LOST
2. Lainassa
3. Varattu (=Noudettavissa)
4. Kuljetuksessa
5. NOT_LOAN
6. Damaged
7. Saatavissa

**Comment by sksandel** [comment]
Vaskin tuotantoon vietiin tänään 26.9. uudet nidetilojen priorisoinnit. Pystyimme muokkaamaan ja testaamaan priorisointien järjestystä itse, kun Kansalliskirjasto laittoi asetukset näkyviin Finnan testinäkymään (ei tuotantonäkymään). Jos joku muu kirjastokimppa haluaa myös muokata asetuksia itse, saa asetukset näkyviin ja muokattaviksi tekemällä pyynnön Finna-postiin. Samalla saa tietää, missä tiedostossa pyynnön tehneen kirjaston asetukset sijaitsevat. Kun priorisoinnit ovat valmiit ja testatut, tehdään myös tuotantoonvientipyyntö Finna-postiin.

Nidetilojen priorisoinnin uudet asetukset Vaskissa listattu alla. 

[StatusRankings]
Lost = 1
Charged = 2
Overdue = 2
On Hold = 3
In Transit = 4
In Transit On Hold = 4
Tilattu = 5 
Saapunut = 5 
Henkilökunnalla = 5 
Ei saatavana, ei varattavissa = 5
Uusin numero, luettavissa kirjastossa = 5 
Korjattavana = 5
Käsiteltävänä = 5
Luettavissa kirjastossa = 5
Laskutettu = 5 
Lisäkappalevarasto = 5
Näyttelyssä = 5
Selvitettävänä = 5
Kotipalvelun käytössä, ei varattavissa = 6
Saatavana, ei varattavissa = 6
Saatavana oppilaille, ei varattavissa = 6
Saatavissa = 7


Näistä rivi On Hold = 3 ei vaikuta toivotusti noudettavana olevaan niteeseen vaan Noudettavana -tila näytetään aina viimeisenä. Noudettavana-tilan kanssa päällekkäisiä muita tiloja ei kuitenkaan pitäisi päästä syntymään. 

NOT_LOAN ja DAMAGED-tilojen nimet otetaan Kohan sarakkeesta Kuvaus (verkkokirjastossa).

**Comment by sksandel** [comment]
Tuotantokäytössä ei ole havaittu ongelmia. Jos uusi priorisointi aiheuttaisi ylimääräistä kuormaa, olisi se varmasti jo tähän mennessä tullut esiin. Suljen tiketin.
