### ISSUE TITLE
Finnassa näkyvien palautuskehotusten otsikon ja selitteiden muutokset

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Finna-kehitysehdotukset#21]
Redminen tiketti: https://tiketti.koha-suomi.fi/issues/5561

Finna-tukeen 11.8.2022 laitettu muutosehdotus:
 
Pyytäisimme Koha-Suomen kirjastojen asiakkaiden maksuissa näkyvän palautuskehotuksen otsikkotietoon ja selitteeseen muutoksia, jotka ilmeisesti pystytään tekemään Finnan päässä.

Tällä hetkellä Finnan näkymä on esim. OUTI-kirjaston asiakkaalla näin:
![image](https://github.com/KohaSuomi/Finna-kehitysehdotukset/assets/98814860/20e7ba48-e8f8-4401-907c-3c25a0de53cb)

-	Voisiko otsikkotiedon ”ei tietoa” korvata vaikka pelkällä viivalla (-), jos otsikossa pitää olla jotain. Ei tietoa -otsikko ei anna asiakkaille luotettavaa kuvaa palvelustamme. 
-	Voisiko ”Overdue” suomentaa ”Palautuskehotus”. Tällöin selite olisi esim. ”Palautuskehotus – 1. huomautus” ja ”Palautuskehotus – 2. huomautus".

Muutokset saisi tehdä kaikille Koha-Suomen kirjastoille.

11.8.2022 Finna-tuesta on vastattu, että ovat parhaillaan tekemässä muutosta ja ovat pyytäneet testikortille palautuskehotukset, jotta voivat testata ja varmistaa muutokset.
Esimerkkitapaukset hoidettu heidän testikortilleen.

15.11.2022 olen kysellyt muutoksen perään, mutten ole saanut vastausta.
14.12.2023 karhuttu taas muutosta Finna-tuelta.

**Comment by pirliis** [comment]
19.12.2023 Finna-tuki ilmoittanut: Palautuskehotuksille Kohasta tuleva ODUE mäpätään myös Finnassa ODUEksi (ennen oli Overdue) ja tekevät sille oletuskäännöksen "Palautuskehotus".

Palautuskehotuksien teksteiksi on Finnaan ehdotettu 21.12.2023 näin, jos on mahdollista toteuttaa:
* suomeksi: ”Palautuskehotus – 1. huomautus” ja ”Palautuskehotus – 2. huomautus"
* englanniksi:  "Overdue notice - 1. reminder" ja "Overdue notice - 2. reminder"
* ruotsiksi: "Påminnelse om försenade lån - 1. påminnelse" ja "Påminnelse om försenade lån - 2. påminnelse"

Tekstille "ei tietoa" saimme Finnasta vastauksen:
_Tekstille "ei tietoa” näyttäisi löytyvän koodi "not_applicable”. Käännöskoodi “not_applicable” on periaatteessa geneerinen käännös. Sitä voi käyttää muuallakin, mutta ei pitäisi olla tällä hetkellä käytössä muualla. Hallintaliittymän kielikäännökset -välilehdellä tuon käännöksen pystyy tyhjentämään syöttämällä "###", jos haluaa tyhjentää käännöksen._

OUTIssa testattiin käännöskoodin “not_applicable” tyhjentämistä ja se toimi eli otsikko on palautuskehotuksien kohdalla tyhjä.

**Comment by pirliis** [comment]
Finna-tuki on laittanut ehdottamamme käännökset kaikkien kimppojen finna-pre:lle. 

Tarkistakaa, että suomen-, enkun- ja ruotsinkieliset käännökset näkyvät palautuskehotuksissa oikein. OUTIssa pystyimme nyt tarkistamaan vain suomenkielisen, joka näkyy ainakin halutulla tavalla:
![image](https://github.com/KohaSuomi/Finna-kehitysehdotukset/assets/98814860/52ee5186-87c1-47e0-89ed-c0e0fb7233b5)

Joulun jälkeen näemme myös OUTIn enkunkieliset.

Kun olette kuittailleet tänne, että käännökset näkyvät teillä oikein, pyydämme Finna-tukea laittamaan ne tuotantoon.

**Comment by pirliis** [comment]
Englanninkieliset palautuskehotukset näkyvät OUTIssa halutulla tavalla:
![image](https://github.com/KohaSuomi/Finna-kehitysehdotukset/assets/98814860/eb95f597-0081-490a-aee4-ea21220d0e98)

**Comment by LeenaKinnunen** [comment]
Lapin Finnassa näkyvät myös oikein molemmilla kielillä.

**Comment by ajrajala** [comment]
Vaskissa tarkistettu suomen ja englannin lisäksi ruotsi. Ruotsiksi näkyy nyt näin:

![kuva](https://github.com/KohaSuomi/Finna-kehitysehdotukset/assets/44638512/40b5d0ef-6ea9-4906-8e3b-22e51bc1af76)

![kuva](https://github.com/KohaSuomi/Finna-kehitysehdotukset/assets/44638512/8800bc57-b454-4e41-b3e7-c58371435a3d)

Alkujaan oli kaiketi pyydetty, että ruotsiksi teksti olisi muotoa "1. påminnelse" ja "2. påminnelse", mutta ilmeisesti tuo "1:a" on oikeampi tapa kirjoittaa tuo järjestysnumero eli eiköhän tuo ruotsikin ole nyt ok. 👍

**Comment by pirliis** [comment]
Palautuskehotusten tekstit ja suomennokset on laitettu nyt kaikkien kimppojen tuotantoon. Tarkistaisitteko, että teillä näkyy tekstit oikein.

**Comment by ajrajala** [comment]
Vaskissa tarkistettu, että fin/swe/eng näkyy kaikki oikein tuotanto-Finnassa.

**Comment by pirliis** [comment]
Kiitos tiedosta, suljen tiketin.
