### ISSUE TITLE
Varaustunnus- ja kutsumanimi-kenttä muutos Finnaan

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Finna-kehitysehdotukset#22]
Varaustunnus on aiemmin tallennettu Kohassa other name -kenttään. Nykyisin siihen käytetään holdid-kenttää. Tämä muutos pitää saada käyttöön kaikille kimpoille myös Finnaan. 

Osa kimpoista ottaa käyttöön kutsumanimi-kentän. Kohassa kutsumanimi tallennetaan other name -kenttään. Finnassa kutsumanimelle käytetään calling_name-kenttää. Muutokset tehdään kaikille kimpoille, mutta vain Vaski- ja OUTI-kimpoissa kutsumanimi kenttä halutaan näkyviin Finnaan asiakkaan Omat tiedot -sivulle.

Edellä mainitut muutokset tehdään ensin kaikkien kimppojen testi-Kohaan ja testi-Finnaan, jotta voidaan varmistaa, että kentät näkyvät kaikilla oikein. OUTIn ja Vaskin testi-Finnoissa kentät näkyvät jo oikein. OUTI pyytää myös muille kimpoille muutokset Finna-testeille. 

Selvitetään, mitä koodimuutoksia kimppojen finna-pääkäyttäjien pitää vielä tehdä, jotta kentät saadaan toimimaan oikein ja miten kutsumanimi-kenttä piilotetaan Finnasta, jos sitä ei haluta näkyville. 

Lari hoitaa Kohan pään kuntoon.

**Comment by pirliis** [comment]
Finna-tuesta kysytty 31.1., millä aikataululla saisivat tehtyä muutokset finna-testeille?

**Comment by lmstrand** [comment]
Testi-Finnoihin tehty pyydetyt muutokset. Kuittaatteko tähän tikettiin, kun olette tarkastaneet, että testi-Finnanne näyttää tiedot oikein ja muutospyyntö onnistuu.

- [x] Vaara
- [x] Kyyti
- [x] Helle
- [x] Vaski
- [x] Outi
- [x] Siili
- [x] Kirkes
- [x] Lumme
- [x] Lappi

**Comment by pirliis** [comment]
OUTIssa varaustunnus ja kutsumanimi näkyvät oikein. Niiden muutokset onnistavat. Myös yhteystietojen muutokset toimivat.

**Comment by pknuuti** [comment]
Vaaran testillä Finnassa muutettu varaustunnus ja kutsumanimi tallentuvat. Kutsumanimi ei näy testivirkailijatyökalussa, koska sitä ei ole määritelty näkymään? Muutettu varaustunnus näkyy kuten pitääkin. Myös osoitteen vaihtaminen onnistuu.

**Comment by rakkyllo** [comment]
Vaskissa molemmat näkyvät profiili-sivulla oikein ja tietojen päivitys testi-Kohan suuntaan toimii, mutta en vielä ruksita kaikkea selväksi. Pitikö varaustunnisteen tulla Finnaan jatkossa holdid-nimiseen kenttään? Koska nyt meillä se tulee hold_identifier-kenttään. Ollaanko siis sittenkin päätetty käyttää hold_identifier-kenttää? Sinällään mulle ei ole väliä, kumpaa käytetään, mutta varmistan vain koska viimeisin muistikuvani on, että oltaisiin siirtymässä käyttämään "holdid"-kenttää 👀

**Comment by lmstrand** [comment]
Kohasta tieto välittyy koodissa holdid -nimisenä muuttujana ja Finnan päässä (driverissa?) tieto siirretään hold_identifier -nimiseen kenttään Finna-liittymässä, joka nyt sinne lisättiin Eren toimesta. Eli kooditasolla puhutaan holdid-muuttujasta, mutta Finnassa sitä käytetään tuossa hold_identifier-nimisessä kentässä.

**Comment by ReettaSiili** [comment]
Siilissä muutospyyntö välittyy testi-Finnasta testi-Kohaan Muu nimi -kenttään, joka oli meillä piilotettuna. Siili ei ole tässä vaiheessa ottamassa ominaisuutta käyttöön, meillä on nyt ollut näkyvissä sukunimi, etunimi, toinen nimi (viimeinen ei pakollinen).

**Comment by Tuomas-Kyyti** [comment]
Kyytin testi-Finnassa onnistui osoitteen, varaustunnuksen ja kutsumanimen muutokset testi-Kohaan.

Emme ainakaan toistaiseksi ota kutsumanimeä käyttöön, joten tarvitaan ohje, miten sen saa osoitteenmuutospyyntö-lomakkeelta piiloon.

Sellaisen eron huomasin, että testi-Finnan numero tekstiviesteille -kentän muutos muuttaa testi-Kohassa numerot matkapuhelin, lankapuhelin ja tekstiviestinumeroon kenttiin. Tuotannossa ei päivitä lankapuhelin-kenttään.

**Comment by Kati-Helle** [comment]
Hellen testi-Finnassa toimii oikein varaustunnuksen, osoitetietojen, matkapuhelinnumeron muutokset.
Tuomaksen mainitsemaa Lankapuhelin-kentän arvon päivittymistä ei tapahdu Hellessä. Testasin niin, että Lankapuhelin-kenttä oli arvoton sekä niin, että Lankapuhelin-kentässä oli arvo. Finnan Numero tekstiviesteille -kentän muutos päivittyi Matkapuhelin-kenttään sekä Tekstiviesti numeroon -kenttään.

Kutsumanimi-kentän arvokin siirtyy Finnasta Kohaan. Näkyy mm. asiakkaan Tiedot-välilehdellä. Kutsumanimi-kenttä ei ole Hellessä käytössä.

**Comment by AnneliO** [comment]
> Sellaisen eron huomasin, että testi-Finnan numero tekstiviesteille -kentän muutos muuttaa testi-Kohassa numerot matkapuhelin, lankapuhelin ja tekstiviestinumeroon kenttiin. Tuotannossa ei päivitä lankapuhelin-kenttään.

Silloin kun yhtenäistettiin puhelinnumerokenttiä, pyydettiin kaikkia kimppoja pyytämään Finna-toimistoa säätämään numerokenttien siirtyminen niin, että tekstiviestinumero menee mobile- ja smsalertnumber-kenttiin. Todennäköisesti muutosta ei ole silloin tehty testi-Finnan puolelle. :)

**Comment by ElinaUotila** [comment]
Kirkesissä on testattu ja toimii, unohdin vain kuitata. Nyt huomasin, että meillä näkyy tuo lankanumerokenttä siellä, eli meilläkään ei ole tehty sitä testi-Finnan puolelle.

**Comment by PiaKusmin** [comment]
Lappikin nyt testattu. Ja meillä sama eli testi-Finnassa onnistui osoitteen, varaustunnuksen ja kutsumanimen muutokset testi-Kohaan.

Emme kuitenkaan (ainakaa vielä) ota kutsumanimeä käyttöön, joten tarvitsisimme myös ohjeen, miten sen saa osoitteenmuutospyyntö-lomakkeelta piiloon.

**Comment by Hanna-Lumme** [comment]
Lumpeilla testattu myös pienten teknisten ongelmien jälkeen. Testi-Finnassa onnistuu osoitteen, varaustunnuksen ja kutsumanimen muutokset testi-Kohaan. 

Mekään emme ole ottamassa kutsumanimeä käyttöön, joten ohjeesta tämän kohdan piilotukseen on myös meillekin hyötyä.

**Comment by pirliis** [comment]
Nyt kaikki ovat testanneet. Kiitos!

Kysytään Finna-tuesta, miten Kutsumanimi-kentän saa piilotettua Omat tiedot -sivulta ja Tee muutospyyntö -lomakkeelta?

**Comment by lmstrand** [comment]
Odotellaan vielä nuo piilotukset kuntoon, niin ehdotan sitten tuotantoonsiirtämistä joksikin tiistaiaamuksi Finna-kehittäjälle.

**Comment by pirliis** [comment]
Okei. Minäpä laitan Finna-tukeen siihen samaan viestiketjuun kysymyksen piilotuksista.

**Comment by pirliis** [comment]
> Okei. Minäpä laitan Finna-tukeen siihen samaan viestiketjuun kysymyksen piilotuksista.

Finna-tuesta vastattu 22.2.20204:
_"Voidaan tehdä niin, ettei laiteta mitään kutsumanimeen liittyvää yhteisiin asetuksiin, jolloin mitään ei oletuksena tule näkyviin. Sitten lisätään Vaskille ja Outille erikseen tarvittavat asetukset."_

**Comment by lmstrand** [comment]
Ehdotin muutosta tuotantoihin jollekin tiistaiaamulle klo 8-9.

**Comment by pirliis** [comment]
Muutokset saadaan tuotantoihin ja nexteille tiistaiaamuna 12.3.2024.

**Comment by pirliis** [comment]
Testasin OUTI-Finnassa. Kutsumanimi- ja Varaustunnus-kentät näkyvät oikein kuin myös kenttien muutospyynnöt ja muutokset. En ainakaan huomannut, että joku paikka olisi mennyt rikki muutosten myötä. :)

**Comment by lmstrand** [comment]
Kaikki tuntuisi olevan kunnossa. Suljen tiketin.
