### ISSUE TITLE
Kohasta tuleville virheilmoituksille kielikäännökset Finnaan

### ISSUE THREAD

**Issue by rakkyllo** [KohaSuomi/Finna-kehitysehdotukset#4]
Olemme törmänneet Finnan puolella joihinkin Kohasta tuleviin virheilmoituksiin, joille ei Finnassa pysty lisäämään kielikäännöksiä. Niinpä virheilmoitukset näkyvät vain englanniksi. Kansalliskirjaston mukaan kielikäännöksiä ei saa lisättyä nykyisellä toteutuksella.

Kyse on seuraavista virheilmoituksista, joita tulee vastaan verkkokirjaston puolella varausta tehdessä:

"The supplied pickup location is not valid"
- On valittu noutopiste, jota varattavalle aineistolle ei voi valita.

"Hold cannot be placed. Reason: noReservesAllowed"
- Asiakkaalla varaus noudettavissa kyseisestä tietueesta, tietueella on Kohassa useampi nide joista yhden nidetyyppi ei salli varaamista (2 x 14VRK ja 1 x 56VRK).

"Hold cannot be placed. Reason: damaged"
- Tietueella on damaged-tilainen nide (esim. Jokeri). Kohan puolella voidaan tehdä varaus ilman varoitusta.

Voitaisiinko näillekin ilmoituksille lisätä tuki Finnaan? Etenkin tukea "The supplied pickup location is not valid" -viestille toivoisimme mahdollisimman pian, jotta voisimme Kohassa ottaa uuden varaussäännön käyttöön.

**Comment by AnneliO** [comment]
Pääkäyttäjäpalaveri 22.8.2023: Vaski voi viedä asiaa eteenpäin Finna-toimistolle.

**Comment by ajrajala** [comment]
Finna-tiketti _(FINNAPOSTI-20335) Kohan virheilmoituksille kielikäännöksiä_ tehty.

**Comment by rakkyllo** [comment]
Kansalliskirjastolta on tullut vastaus 4.9.2023. Tästä on tehty kehitysehdotus, joten jäädään odottelemaan milloin toteutus tulee Finnaan. Suljen tiketin tällä erää.

**Comment by rakkyllo** [comment]
Kommentoin jälkikäteen tiedoksi: kielikäännöksiä voi lisätä tällaisille teksteille yksinkertaisesti siten, että laittaa käännettävän tekstin kielikäännöstiedostoon (esim. local/languages/fi.ini) ilman lainausmerkkejä. Esimerkki:

`The supplied pickup location is not valid = "Haluttu käännös."`
