### ISSUE TITLE
Varauksen alkamispäivän muuttaminen

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Finna-kehitysehdotukset#6]
Jos asiakas haluaa tehdä varauksen, joka ei astu voimaan heti vaan vasta myöhemmin, hänen täytyy tehdä se kiertoteitse: tehdä varaus ja jäädyttää se tiettyyn päivämäärään saakka. Olisiko mahdollista saada asiakkaan tehdä varaus alkamaan suoraan tietystä päivämäärästä?

**Comment by sksandel** [comment]
11.10.2024 Yhteinen läpikäynti. Kaikilla ei käytössä alkamispäivämäärän valintaa. Asiakkaan on kuitenkin mahdollisuus toimia yllä kuvatulla tavalla. 

Hylätään
