### ISSUE TITLE
Varaustunnus näkyville varauksen noutotietoon

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Finna-kehitysehdotukset#8]
Onko Kohassa mahdollisuus saada Finnaan näkyville asiakkaan varaustunnus, kun asiakas katsoo Finnan kautta varauksiaan ja siellä näkyy noudettavia varauksia. Mukana kuva, jossa Aurora-kirjaston näkymä vastaavasta tilanteesta.

![2023kuvat 202](https://github.com/KohaSuomi/Finna-kehitysehdotukset/assets/73887264/6c65fe92-222f-4bf7-9c92-48989ad70ced)

**Comment by sksandel** [comment]
11.10.2024 Yhteinen läpikäynti. Jos varaustunnus vaihtuu, mitä silloin näytetään? Järjestelmästä tulee vain voimassaoleva tunnus. Asiakkaan pitäisi toimia saapumisilmoituksen mukaan. 

Hylätään.
